#!/bin/bash
# Setup PipeWire virtual I/O devices for Apollo x4
# Discovers Apollo ALSA nodes dynamically, sets pro-audio profile,
# and generates loopback config with correct channel targets.
#
# Run after PipeWire/WirePlumber start:
#   bash ~/apollo-linux/configs/pipewire/setup-apollo-io.sh
#
# Can also be called from a systemd user service.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pipewire/pipewire.conf.d"
CONF_FILE="$CONF_DIR/apollo-io-map.conf"

MAX_WAIT=10  # seconds to wait for PipeWire

# ── Helpers ──

log() { echo "[apollo-io] $*"; }
die() { log "ERROR: $*" >&2; exit 1; }

wait_for_pipewire() {
    local i=0
    while ! pw-cli info 0 &>/dev/null; do
        sleep 1
        i=$((i + 1))
        [ $i -ge $MAX_WAIT ] && die "PipeWire not responding after ${MAX_WAIT}s"
    done
}

# ── Step 1: Wait for PipeWire ──

log "Waiting for PipeWire..."
wait_for_pipewire
log "PipeWire is up"

# ── Step 2: Find Apollo ALSA device and set pro-audio profile ──

# Find the device ID by matching "Apollo" in wpctl device list
DEVICE_ID=$(wpctl status 2>/dev/null | grep 'Apollo x4' | grep '\[alsa\]' | grep -oP '[0-9]+' | head -1 || true)

# Fallback: search pw-dump for driver name
if [ -z "$DEVICE_ID" ]; then
    DEVICE_ID=$(pw-dump 2>/dev/null | python3 -c "
import json, sys
for obj in json.load(sys.stdin):
    props = obj.get('info', {}).get('props', {})
    if props.get('alsa.driver_name') == 'ua_apollo' and obj.get('type') == 'PipeWire:Interface:Device':
        print(obj['id']); break
" 2>/dev/null || true)
fi

if [ -z "$DEVICE_ID" ]; then
    die "Apollo device not found in PipeWire. Is the driver loaded?"
fi

log "Found Apollo device ID: $DEVICE_ID"

# Set pro-audio profile (index 1) — required for multi-channel access
# WirePlumber's alsa_monitor.rules doesn't auto-select pro-audio
if wpctl set-profile "$DEVICE_ID" 1 2>/dev/null; then
    log "Set pro-audio profile on device $DEVICE_ID"
else
    log "Warning: failed to set pro-audio profile (may already be set)"
fi

# Brief pause for node creation after profile change
sleep 1

# ── Step 3: Discover ALSA node names ──

# Find Apollo pro-audio node names via pw-dump (reliable, handles any PCI address)
eval "$(pw-dump 2>/dev/null | python3 -c "
import json, sys
data = json.load(sys.stdin)
inp = out = ''
for obj in data:
    props = obj.get('info', {}).get('props', {})
    if props.get('alsa.driver_name') != 'ua_apollo': continue
    name = props.get('node.name', '')
    if 'input' in name and not inp: inp = name
    if 'output' in name and not out: out = name
print(f'INPUT_NODE=\"{inp}\"')
print(f'OUTPUT_NODE=\"{out}\"')
" 2>/dev/null || echo 'INPUT_NODE="" ; OUTPUT_NODE=""')"

[ -z "$INPUT_NODE" ] && die "Apollo pro-audio input node not found. Is pro-audio profile active?"
[ -z "$OUTPUT_NODE" ] && die "Apollo pro-audio output node not found. Is pro-audio profile active?"

log "Input node:  $INPUT_NODE"
log "Output node: $OUTPUT_NODE"

# ── Step 4: Generate loopback config ──
#
# Apollo x4 channel map at 48kHz:
#
# CAPTURE (22ch, AUX0-21):
#   AUX0-1:   Mic/Line/HiZ 1-2
#   AUX2-3:   Mic/Line 3-4
#   AUX4-5:   S/PDIF L/R
#   AUX6-13:  Virtual 1-8
#   AUX14-15: Mon L/R
#   AUX16-17: AUX1 L/R
#   AUX18-19: AUX2 L/R
#   AUX20-21: Talkback 1-2
#
# PLAYBACK (24ch, AUX0-23):
#   AUX0-1:   Mon L/R
#   AUX2-5:   Line 1-4
#   AUX6-7:   S/PDIF L/R
#   AUX8-15:  Virtual 1-8
#   AUX16-17: CUE1 L/R
#   AUX18-19: CUE2 L/R
#   AUX20-21: CUE3 L/R
#   AUX22-23: CUE4 L/R

mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" << CONF
# Auto-generated by setup-apollo-io.sh — do not edit manually
# Apollo x4 virtual I/O devices mapped to pro-audio channels
# Input: $INPUT_NODE | Output: $OUTPUT_NODE

context.modules = [

    # ═══════════════════════════════════════════
    # CAPTURE SOURCES (Apollo → PipeWire)
    # Pattern from PipeWire docs: capture side targets ALSA input (passive),
    # playback side presents as Audio/Source for apps to read from.
    # ═══════════════════════════════════════════

    # Mic 1 (mono)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 1"
            capture.props = {
                audio.position      = [ AUX0 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_mic_1"
                media.class         = "Audio/Source"
                audio.position      = [ MONO ]
            }
        }
    }

    # Mic 2 (mono)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 2"
            capture.props = {
                audio.position      = [ AUX1 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_mic_2"
                media.class         = "Audio/Source"
                audio.position      = [ MONO ]
            }
        }
    }

    # Mic 1+2 Stereo
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 1+2"
            capture.props = {
                audio.position      = [ AUX0 AUX1 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_mic_stereo"
                media.class         = "Audio/Source"
                audio.position      = [ FL FR ]
            }
        }
    }

    # Mic 3 (mono) — Line 3
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 3"
            capture.props = {
                audio.position      = [ AUX2 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_mic_3"
                media.class         = "Audio/Source"
                audio.position      = [ MONO ]
            }
        }
    }

    # Mic 4 (mono) — Line 4
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Mic 4"
            capture.props = {
                audio.position      = [ AUX3 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_mic_4"
                media.class         = "Audio/Source"
                audio.position      = [ MONO ]
            }
        }
    }

    # Line 3+4 (stereo)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Line In 3+4"
            capture.props = {
                audio.position      = [ AUX2 AUX3 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_line_34"
                media.class         = "Audio/Source"
                audio.position      = [ FL FR ]
            }
        }
    }

    # Talkback Mic: capture AUX20-21, but requires DSP MODULE_ACTIVATE
    # (PostConnect ring command) to produce signal. Not yet implemented.
    # See: plans/260318-0901-capture-postconnect/plan.md

    # S/PDIF In (stereo capture) — UNTESTED: needs S/PDIF source connected
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo S/PDIF In"
            capture.props = {
                audio.position      = [ AUX4 AUX5 ]
                stream.dont-remix   = true
                node.target         = "$INPUT_NODE"
                node.passive        = true
            }
            playback.props = {
                node.name           = "apollo_spdif_in"
                media.class         = "Audio/Source"
                audio.position      = [ FL FR ]
            }
        }
    }

    # ═══════════════════════════════════════════
    # PLAYBACK SINKS (PipeWire → Apollo)
    # Pattern: capture side = Audio/Sink (apps write here),
    # playback side targets ALSA output (NOT passive — must drive output).
    # ═══════════════════════════════════════════

    # Monitor L/R (main speakers)
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Monitor L/R"
            capture.props = {
                node.name           = "apollo_monitor"
                media.class         = "Audio/Sink"
                audio.position      = [ FL FR ]
            }
            playback.props = {
                node.target         = "$OUTPUT_NODE"
                audio.position      = [ AUX0 AUX1 ]
                stream.dont-remix   = true
            }
        }
    }

    # Line Out 1+2
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Line Out 1+2"
            capture.props = {
                node.name           = "apollo_line_out_12"
                media.class         = "Audio/Sink"
                audio.position      = [ FL FR ]
            }
            playback.props = {
                node.target         = "$OUTPUT_NODE"
                audio.position      = [ AUX2 AUX3 ]
                stream.dont-remix   = true
            }
        }
    }

    # Line Out 3+4
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo Line Out 3+4"
            capture.props = {
                node.name           = "apollo_line_out_34"
                media.class         = "Audio/Sink"
                audio.position      = [ FL FR ]
            }
            playback.props = {
                node.target         = "$OUTPUT_NODE"
                audio.position      = [ AUX4 AUX5 ]
                stream.dont-remix   = true
            }
        }
    }

    # S/PDIF Out (stereo playback) — UNTESTED: needs S/PDIF receiver connected
    { name = libpipewire-module-loopback
        args = {
            node.description = "Apollo S/PDIF Out"
            capture.props = {
                node.name           = "apollo_spdif_out"
                media.class         = "Audio/Sink"
                audio.position      = [ FL FR ]
            }
            playback.props = {
                node.target         = "$OUTPUT_NODE"
                audio.position      = [ AUX6 AUX7 ]
                stream.dont-remix   = true
            }
        }
    }
]
CONF

log "Generated config: $CONF_FILE"
log "  Sources: Mic 1-4, Mic 1+2 (stereo), Line In 3+4 (stereo), S/PDIF In"
log "  Sinks:   Monitor L/R, Line Out 1+2, Line Out 3+4, S/PDIF Out"

# ── Step 5: Restart PipeWire to load the config ──

# PipeWire reads conf.d on startup, so we need a restart to pick up the new config.
if systemctl --user is-active pipewire.service &>/dev/null; then
    log "Restarting PipeWire to load new config..."
    systemctl --user restart pipewire.service
    sleep 2
    wait_for_pipewire

    # Re-set pro-audio profile after restart (lost during restart)
    sleep 1
    NEW_DEVID=$(wpctl status 2>/dev/null | grep 'Apollo x4' | grep '\[alsa\]' | grep -oP '[0-9]+' | head -1 || true)
    if [ -n "$NEW_DEVID" ]; then
        wpctl set-profile "$NEW_DEVID" 1 2>/dev/null || true
        log "Re-set pro-audio profile (device $NEW_DEVID)"
    fi
fi

# ── Step 6: Verify ──

sleep 2
SOURCES=$(wpctl status 2>/dev/null | grep -c 'Apollo' || echo 0)
log "Apollo nodes visible in wpctl: $SOURCES"

if [ "$SOURCES" -gt 0 ]; then
    log "Setup complete!"
else
    log "Warning: no Apollo virtual nodes found. Check: wpctl status"
fi
